### ISSUE TITLE
Recoil 설치 및 Tailwind CSS custom templete 생성

### ISSUE THREAD

**Issue by YueunKim** [pie-sfac/1-16-careMango#6]
To do

- [x] Recoil 설치 
- [x] Tailwind CSS custom class 생성 - input과 select 
- [x] Tailwind CSS custom color palette 생성
- [x] font (pretandard) 설정

**Comment by s-ja** [comment]
PR 승인 및 병합 완료하였습니다. 깃헙에서 보이는 코드에는 이상 없는 것으로 보여, 브랜치 삭제 및 이슈 닫겠습니다.
